version: '3.8'

services:
  # Serviço nginx
  nginx:
    image: nginx:alpine
    container_name: dezsaudefarma-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/log/nginx
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./dist:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - dezsaudefarma-network

networks:
  dezsaudefarma-network:
    driver: bridge 